replicaCount: 1

webserver:
  image:
    repository: lcatricity-dashboard-image
    tag: latest
  port: 80

api:
  image:
    repository: lcatricity-api-image
    tag: latest
  port: 9000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi